name = "codeassylum-comingsoon"
main = "index.js"
compatibility_date = "2025-09-04"

kv_namespaces = [
  { binding = "CODEASYLUM_SIGNUPS", id = "your-kv-namespace-id" }
]

[site]
bucket = "./public"
entry-point = "workers-site"

[vars]
COMPANY_NAME = "Code Assylum"
AUTHOR_NAME = "Prince Jagaban (The Tech Monarch)"
